// Code generated by protoc-gen-go.
// source: types.proto
// DO NOT EDIT!

/*
Package internal is a generated protocol buffer package.

Package internal holds protobuf types used by the server

It is generated from these files:
	types.proto

It has these top-level messages:
	RefreshToken
	IDTokenSubject
*/
package internal

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// RefreshToken is a message that holds refresh token data used by dex.
type RefreshToken struct {
	RefreshId string `protobuf:"bytes,1,opt,name=refresh_id" json:"refresh_id,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *RefreshToken) Reset()         { *m = RefreshToken{} }
func (m *RefreshToken) String() string { return proto.CompactTextString(m) }
func (*RefreshToken) ProtoMessage()    {}

// IDTokenSubject represents both the userID and connID which is returned
// as the "sub" claim in the ID Token.
type IDTokenSubject struct {
	UserId    string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	ConnId    string `protobuf:"bytes,2,opt,name=conn_id" json:"conn_id,omitempty"`
	SubConnId string `protobuf:"bytes,3,opt,name=sub_conn_id" json:"sub_conn_id,omitempty"`
}

func (m *IDTokenSubject) Reset()         { *m = IDTokenSubject{} }
func (m *IDTokenSubject) String() string { return proto.CompactTextString(m) }
func (*IDTokenSubject) ProtoMessage()    {}

func init() {
}
